# Generated by Django 2.2.2 on 2019-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0002_remove_method_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='request',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
