# Generated by Django 2.2.2 on 2019-07-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0004_auto_20190718_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='request',
        ),
    ]
